### ISSUE TITLE
Is fine_tuning ever used as an option ?

### ISSUE THREAD

**Issue by skol101** [yuan1615/AdaVocoder#6]
Is it ever used in either Hifi-Gan or Ada training steps?

**Comment by yuan1615** [comment]
I think the "fine_tuning" you said here refers to the hifi-gan thesis. It mainly solves the problem of feature mismatch, that is to say, the mel spectrum generated by the acoustic model does not match the original mel spectrum, so it is necessary to use the mel spectrum generated by the acoustic model to "fine_tuning" the trained vocoder. 

I did this when building the Custom Voice system.

I don't recommend training adavocoder when you have enough quality data, because it's good enough to train a robust enough vocoder.

**Comment by skol101** [comment]
Thanks
